[package]
name = "spexia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
rustfft = "6.1.0"
gl = "0.14.0"
glfw = "0.55.0"
